services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql-init.d:/docker-entrypoint-initdb.d